name: BlockedInCombat
version: 1.1.1
author: kinj14
main: fr.kinj14.blockedincombat.Main
api-version: 1.13
website: https://github.com/Linj1k

commands:
  blockedincombat:
    description: Information about BlockedInCombat
    usage: "Usage: /blockedincombat"
    aliases:
      - blockedincombat
  blockedincombat.devmode:
    description: Allows you to try the game mode without other players
    permission: blockedincombat.*
    usage: "Usage: /devmode"
    aliases:
      - devmode
  blockedincombat.settings:
    description: Open Settings GUI
    permission: blockedincombat.ChangeSettings
    usage: "Usage: /settings"
    aliases:
      - settings
  blockedincombat.arena:
    description: setup,setup clear,generate,finish,clear and teleport to arena
    permission: blockedincombat.Arena
    usage: "Usage: /arena setup/setupclear/build/finish/clear/tp"
    aliases:
      - arena
  blockedincombat.cancel:
    description: Cancel the game
    permission: blockedincombat.ChangeSettings
    aliases:
      - cancel
  blockedincombat.canbuild:
    description: build or destroy blocks even when the game hasn't started
    permission: blockedincombat.canbuild
    usage: "Usage: /canbuild"
    aliases:
      - canbuild
  blockedincombat.stats:
    description: Look at your stats or those of others (Wins, kills and more)
    usage: "Usage: /stats {PlayerName}"
    aliases:
      - stats

permissions:
  blockedincombat.*:
    description: Gives access to *
  blockedincombat.Arena:
    description: Gives access to Arena Commands
  blockedincombat.canbuild:
    description: Gives access to build mode
  blockedincombat.ChangeSettings:
    description: Gives access to ChangeSettings
  blockedincombat.LoadProfiles:
    description: Gives access to Load Profiles
  blockedincombat.SaveProfiles:
    description: Gives access to Save Profiles
  blockedincombat.EditProfiles:
    description: Gives access to Edit Profiles