General:
  devmode: false #Allows you to try the game mode without other players
  WorldName: "world"
  UsebStats: true # true = activates the statistics system
  CheckUpdate: true # true = activates the checkUpdate system
  NoChatFlood: true # true = No chat Flood
  ChatFormat: "{DisplayName}: {Message}" #{DisplayName}, {PlayerName}, {Level}, {Health}, {Food}, {MaxHealth}, {CustomName}, {Gamemode}, {Locale}, {PlayerListName}, {World}, {Message}
  PingInTab: false # true = see ping in the tab
  UpdatePing: 3 # > 0 | Must be greater than 0 to avoid bugs
  YourIP: "&eyour-ip"

Locations:
  Lobby: 47.5, 8, 79.5, 180f, -13.9f # The location of your lobby (XYZ,Facing)

BungeeCord:
  Support: false #true = Your server is on a bungeecord proxy
  Server: "lobby1" #server name of your bungeecord hub